POST http://localhost:8080/patients
Content-Type: application/json

{
    "name": "Sai Teja Palla",
    "email":"pallatej7@gmail.com",
    "address": "213 second street",
    "dateOfBirth": "2000-03-25",
    "registeredDate": "2025-07-04"
}