# update an existing entity

PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174013
Content-Type: application/json

{
    "name": "Palla Sai Tejaa",
    "email": "hey@gmail.com",
    "address": "213 second street",
    "dateOfBirth": "2000-03-25"
}
